title: Watch and learn
description: To be a fucking genius
template:
  repo: watch-and-learn-template
  name: watch-and-learn
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
